version: '{build}'
image:
  - Ubuntu
pull_requests:
  do_not_increment_build_number: true
environment:
  CODECOV_TOKEN:
    secure: CxcArsCpHjUEEH5FZ8FQSoWciGgA7wJ//GdTayc66JQ+kV7I3enTMmhhAo117PXy
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- sh: ./build.sh
after_build:
- sh: ./package.sh
test_script:
- sh: ./test.sh
after_test:
- sh: curl https://codecov.io/bash -o codecov.sh
- sh: chmod +x ./codecov.sh
- sh: ./codecov.sh -f ./coverage/coverage.opencover.xml -X gcov -X coveragepy
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: ptJ1xOgh7IPWlk1romGqz589DLYuuVWeJdixYtc1CgpN3ZUmQY1PMjSXrVYpY/uW
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
